[workspace]
authors = ["michbelle <mi94bell@gmail.com>"]
channels = ["conda-forge", "https://prefix.dev/robostack-kilted"]
name = "braccio_control"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build_zenoh_c = "mkdir -p src/zenoh-c/build && cd src/zenoh-c/build && cmake .. -DCMAKE_INSTALL_PREFIX=../../../.pixi/envs/default && cmake --build . --target install" 
build_zenoh_cpp = "mkdir -p src/zenoh-cpp/build && cd src/zenoh-cpp/build && cmake .. -DCMAKE_INSTALL_PREFIX=../../../.pixi/envs/default && cmake --build . --target install" 
# build_ros = "colcon build --symlink-install --packages-select braccio_control braccio_simulation braccio_moveit --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"
build_ros = "colcon build --symlink-install --packages-select braccio_control braccio_simulation braccio_moveit"
run_ctrl = "ros2 launch braccio_control braccio_controller.launch.py"
# run = "ros2 launch braccio_control send_trajectory.launch.py"
run = "python src/braccio_control/braccio_control/send_trajectory_py.py"
run_joy = "ros2 run joy joy_node"
run_moveit_demo = "LC_ALL=C ros2 launch braccio_moveit demo.launch.py"
#
clean_r = "rm -r build log install"
#
# eval "$(register-python-argcomplete ros2)"

build_rs = "cd src/braccio_planning && cargo build"


# Dependencies used by all environments
[dependencies]
python = "*"
# Build tools
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
# ROS specific tools
rosdep = "*"
colcon-common-extensions = "*"
rust = "*"
gz-sim = "*"

zenoh = ">=1.9.0,<2"
zenoh-pico = ">=1.8.0,<2"
libzenohcxx = ">=1.9.0,<2"

scipy = ">=1.17.1,<2"
filelock = ">=3.29.0,<4"
libgl-devel = ">=1.7.0,<2"


[environments]
kilted = { features = ["kilted"] }
lyrical = { features = ["lyrical"] }


[feature.kilted]
channels = ["https://prefix.dev/robostack-kilted"]

[feature.kilted.dependencies]
ros-kilted-desktop = "*"
ros-kilted-ros2-control = "*"
ros-kilted-ros2-control-cmake = "*"
ros-kilted-backward-ros = "*"
ros-kilted-pluginlib = "*"
ros-kilted-kdl-parser = "*"
ros-kilted-controller-interface = "*"
ros-kilted-control-msgs = "*"
ros-kilted-hardware-interface = "*"
ros-kilted-rclcpp-lifecycle = "*"
ros-kilted-rclcpp = "*"
ros-kilted-realtime-tools = "*"
ros-kilted-trajectory-msgs = "*"
ros-kilted-joy = "*"
ros-kilted-sensor-msgs = "*"
ros-kilted-controller-manager = "*"
ros-kilted-joint-state-broadcaster = "*"
ros-kilted-joint-state-publisher-gui = "*"
ros-kilted-launch-ros = "*"
ros-kilted-launch = "*"
ros-kilted-robot-state-publisher = "*"
ros-kilted-ros2controlcli = "*"
ros-kilted-ros2launch = "*"
ros-kilted-rviz2 = "*"
ros-kilted-urdf = "*"
ros-kilted-xacro = "*"
ros-kilted-ament-cmake-pytest = "*"
ros-kilted-ament-cmake-ros = "*"
ros-kilted-launch-testing-ament-cmake = "*"
ros-kilted-launch-testing = "*"
ros-kilted-rclpy = "*"
ros-kilted-ament-cmake = "*"
ros-kilted-moveit = "*"
ros-kilted-moveit-setup-assistant = "*"
ros-kilted-moveit-ros-move-group = "*"
ros-kilted-moveit-kinematics = "*"
ros-kilted-moveit-planners = "*"
ros-kilted-moveit-simple-controller-manager = "*"
ros-kilted-joint-state-publisher = "*"
ros-kilted-tf2-ros = "*"
ros-kilted-moveit-configs-utils = "*"
ros-kilted-moveit-ros-visualization = "*"
ros-kilted-moveit-ros-warehouse = "*"
ros-kilted-rviz-common = "*"
ros-kilted-rviz-default-plugins = "*"
ros-kilted-moveit-ros-perception = "*"
ros-kilted-joint-trajectory-controller = "*"
ros-kilted-ament-cmake-python = "*"


[feature.lyrical]
channels = ["https://prefix.dev/robostack-lyrical"]

[feature.lyrical.dependencies]
ros-lyrical-desktop = "*"
ros-lyrical-ros2-control = "*"
ros-lyrical-ros2-control-cmake = "*"
ros-lyrical-backward-ros = "*"
ros-lyrical-pluginlib = "*"
ros-lyrical-kdl-parser = "*"
ros-lyrical-controller-interface = "*"
ros-lyrical-control-msgs = "*"
ros-lyrical-hardware-interface = "*"
ros-lyrical-rclcpp-lifecycle = "*"
ros-lyrical-rclcpp = "*"
ros-lyrical-realtime-tools = "*"
ros-lyrical-trajectory-msgs = "*"
ros-lyrical-joy = "*"
ros-lyrical-sensor-msgs = "*"
ros-lyrical-controller-manager = "*"
ros-lyrical-joint-state-broadcaster = "*"
ros-lyrical-joint-state-publisher-gui = "*"
ros-lyrical-launch-ros = "*"
ros-lyrical-launch = "*"
ros-lyrical-robot-state-publisher = "*"
ros-lyrical-ros2controlcli = "*"
ros-lyrical-ros2launch = "*"
ros-lyrical-rviz2 = "*"
ros-lyrical-urdf = "*"
ros-lyrical-xacro = "*"
ros-lyrical-ament-cmake-pytest = "*"
ros-lyrical-ament-cmake-ros = "*"
ros-lyrical-launch-testing-ament-cmake = "*"
ros-lyrical-launch-testing = "*"
ros-lyrical-rclpy = "*"
ros-lyrical-ament-cmake = "*"
ros-lyrical-moveit = "*"
ros-lyrical-moveit-setup-assistant = "*"
ros-lyrical-moveit-ros-move-group = "*"
ros-lyrical-moveit-kinematics = "*"
ros-lyrical-moveit-planners = "*"
ros-lyrical-moveit-simple-controller-manager = "*"
ros-lyrical-joint-state-publisher = "*"
ros-lyrical-tf2-ros = "*"
ros-lyrical-moveit-configs-utils = "*"
ros-lyrical-moveit-ros-visualization = "*"
ros-lyrical-moveit-ros-warehouse = "*"
ros-lyrical-rviz-common = "*"
ros-lyrical-rviz-default-plugins = "*"
ros-lyrical-moveit-ros-perception = "*"
ros-lyrical-joint-trajectory-controller = "*"
ros-lyrical-ament-cmake-python = "*"


[activation]
scripts = ["install/setup.bash"]
# eval "$(register-python-argcomplete ros2)"
