KDL: KDL::Vector2 Class Reference
KDL::Vector2 Class Reference
2D version of Vector
#include <src/frames.hpp>
Public Member Functions
Vector2 ()
Does not initialise to Zero().
Vector2 (double x, double y)
Vector2 (const Vector2 &arg)
Vector2 & operator= (const Vector2 &arg)
double operator() (int index) const
Access to elements, range checked when NDEBUG is not set, from 0..1.
double & operator() (int index)
Access to elements, range checked when NDEBUG is not set, from 0..1.
double operator[] (int index) const
Equivalent to double operator()(int index) const.
double & operator[] (int index)
Equivalent to double& operator()(int index)
double x () const
double y () const
void x (double)
void y (double)
void ReverseSign ()
Vector2 & operator-= (const Vector2 &arg)
Vector2 & operator+= (const Vector2 &arg)
double Normalize (double eps=epsilon)
Normalizes this vector and returns it norm makes v a unitvector and returns the norm of v.
double Norm (double eps=epsilon) const
void Set3DXY (const Vector &v)
projects v in its XY plane, and sets *this to these values
void Set3DYZ (const Vector &v)
projects v in its YZ plane, and sets *this to these values
void Set3DZX (const Vector &v)
projects v in its ZX plane, and sets *this to these values
void Set3DPlane (const Frame &F_someframe_XY, const Vector &v_someframe)
projects v_someframe in the XY plane of F_someframe_XY, and sets *this to these values expressed wrt someframe.
Static Public Member Functions
static Vector2 Zero ()
Private Attributes
double data [2]
Friends
class Rotation2
Vector2 operator* (const Vector2 &lhs, double rhs)
Vector2 operator* (double lhs, const Vector2 &rhs)
Vector2 operator/ (const Vector2 &lhs, double rhs)
Vector2 operator+ (const Vector2 &lhs, const Vector2 &rhs)
Vector2 operator- (const Vector2 &lhs, const Vector2 &rhs)
Vector2 operator* (const Vector2 &lhs, const Vector2 &rhs)
Vector2 operator- (const Vector2 &arg)
void SetToZero (Vector2 &v)
bool Equal (const Vector2 &a, const Vector2 &b, double eps)
do not use operator == because the definition of Equal(.,.) is slightly different.
bool operator== (const Vector2 &a, const Vector2 &b)
The literal equality operator==(), also identical.
bool operator!= (const Vector2 &a, const Vector2 &b)
The literal inequality operator!=().
Detailed Description
2D version of Vector
Constructor & Destructor Documentation
Vector2() [1/3]
KDL::Vector2::Vector2 () inline
Does not initialise to Zero().
References data.
Referenced by Normalize(), and Zero().
Vector2() [2/3]
IMETHOD Vector2::Vector2 (double x, double y) inline
References data, x(), and y().
Vector2() [3/3]
IMETHOD Vector2::Vector2 (const Vector2 & arg) inline
References data.
Member Function Documentation
Norm()
double KDL::Vector2::Norm (double eps = epsilon) const
Returns
the norm of the vector
References data.
Referenced by Normalize().
Normalize()
double KDL::Vector2::Normalize (double eps = epsilon)
Normalizes this vector and returns it norm makes v a unitvector and returns the norm of v.
if v is smaller than eps, Vector(1,0,0) is returned with norm 0. if this is not good, check the return value of this method.
References Norm(), and Vector2().
operator()() [1/2]
IMETHOD double & Vector2::operator() (int index) inline
Access to elements, range checked when NDEBUG is not set, from 0..1.
References data.
operator()() [2/2]
IMETHOD double Vector2::operator() (int index) const inline
Access to elements, range checked when NDEBUG is not set, from 0..1.
References data.
Referenced by operator[](), and operator[]().
operator+=()
IMETHOD Vector2 & Vector2::operator+= (const Vector2 & arg) inline
References data.
operator-=()
IMETHOD Vector2 & Vector2::operator-= (const Vector2 & arg) inline
References data.
operator=()
IMETHOD Vector2 & Vector2::operator= (const Vector2 & arg) inline
References data.
operator[]() [1/2]
double & KDL::Vector2::operator[] (int index) inline
Equivalent to double& operator()(int index)
References operator()().
operator[]() [2/2]
double KDL::Vector2::operator[] (int index) const inline
Equivalent to double operator()(int index) const.
References operator()().
ReverseSign()
IMETHOD void Vector2::ReverseSign () inline
References data.
Referenced by KDL::Frame2::SetInverse().
Set3DPlane()
IMETHOD void Vector2::Set3DPlane (const Frame & F_someframe_XY, const Vector & v_someframe) inline
projects v_someframe in the XY plane of F_someframe_XY, and sets *this to these values expressed wrt someframe.
References data, and KDL::Frame::Inverse().
Set3DXY()
IMETHOD void Vector2::Set3DXY (const Vector & v) inline
projects v in its XY plane, and sets *this to these values
References data.
Set3DYZ()
IMETHOD void Vector2::Set3DYZ (const Vector & v) inline
projects v in its YZ plane, and sets *this to these values
References data.
Set3DZX()
IMETHOD void Vector2::Set3DZX (const Vector & v) inline
projects v in its ZX plane, and sets *this to these values
References data.
x() [1/2]
IMETHOD double Vector2::x () const inline
References data.
Referenced by Vector2().
x() [2/2]
void KDL::Vector2::x (double) inline
y() [1/2]
IMETHOD double Vector2::y () const inline
References data.
Referenced by Vector2().
y() [2/2]
void KDL::Vector2::y (double) inline
Zero()
IMETHOD Vector2 Vector2::Zero () inline static
Returns
a zero 2D vector.
References Vector2().
Referenced by KDL::Frame2::Frame2(), KDL::Frame2::SetIdentity(), and SetToZero().
Friends And Related Symbol Documentation
Equal
bool Equal (const Vector2 & a, const Vector2 & b, double eps) friend
do not use operator == because the definition of Equal(.,.) is slightly different.
It compares whether the 2 arguments are equal in an eps-interval
operator!=
bool operator!= (const Vector2 & a, const Vector2 & b) friend
The literal inequality operator!=().
operator* [1/3]
Vector2 operator* (const Vector2 & lhs, const Vector2 & rhs) friend
operator* [2/3]
Vector2 operator* (const Vector2 & lhs, double rhs) friend
operator* [3/3]
Vector2 operator* (double lhs, const Vector2 & rhs) friend
operator+
Vector2 operator+ (const Vector2 & lhs, const Vector2 & rhs) friend
operator- [1/2]
Vector2 operator- (const Vector2 & arg) friend
operator- [2/2]
Vector2 operator- (const Vector2 & lhs, const Vector2 & rhs) friend
operator/
Vector2 operator/ (const Vector2 & lhs, double rhs) friend
operator==
bool operator== (const Vector2 & a, const Vector2 & b) friend
The literal equality operator==(), also identical.
Rotation2
friend class Rotation2 friend
SetToZero
void SetToZero (Vector2 & v) friend
Member Data Documentation
data
double KDL::Vector2::data[2] private
Referenced by KDL::Rotation2::Inverse(), Norm(), operator()(), operator()(), KDL::Rotation2::operator*(), operator+=(), operator-=(), operator=(), ReverseSign(), Set3DPlane(), Set3DXY(), Set3DYZ(), Set3DZX(), Vector2(), Vector2(), Vector2(), x(), and y().
The documentation for this class was generated from the following files:
src/frames.hpp
src/frames.cpp
src/frames.inl