KDL: KDL::TreeFkSolverPos_recursive Class Reference
KDL::TreeFkSolverPos_recursive Class Reference
Kinematic Families
Implementation of a recursive forward position kinematics algorithm to calculate the position transformation from joint space to Cartesian space of a general kinematic tree (KDL::Tree).
#include <src/treefksolverpos_recursive.hpp>
Public Member Functions
TreeFkSolverPos_recursive (const Tree &tree)
~TreeFkSolverPos_recursive ()
virtual int JntToCart (const JntArray &q_in, Frame &p_out, std::string segmentName)
Calculate forward position kinematics for a KDL::Tree, from joint coordinates to cartesian pose.
Private Member Functions
Frame recursiveFk (const JntArray &q_in, const SegmentMap::const_iterator &it)
Private Attributes
const Tree tree
Detailed Description
Implementation of a recursive forward position kinematics algorithm to calculate the position transformation from joint space to Cartesian space of a general kinematic tree (KDL::Tree).
Constructor & Destructor Documentation
TreeFkSolverPos_recursive()
KDL::TreeFkSolverPos_recursive::TreeFkSolverPos_recursive (const Tree & tree)
~TreeFkSolverPos_recursive()
KDL::TreeFkSolverPos_recursive::~TreeFkSolverPos_recursive ()
Member Function Documentation
JntToCart()
int KDL::TreeFkSolverPos_recursive::JntToCart (const JntArray & q_in, Frame & p_out, std::string segmentName) virtual
Calculate forward position kinematics for a KDL::Tree, from joint coordinates to cartesian pose.
Parameters
q_in input joint coordinates
p_out reference to output cartesian pose
Returns
if < 0 something went wrong
Implements KDL::TreeFkSolverPos.
References KDL::Tree::getNrOfJoints(), KDL::Tree::getSegment(), KDL::Tree::getSegments(), recursiveFk(), KDL::JntArray::rows(), and tree.
recursiveFk()
Frame KDL::TreeFkSolverPos_recursive::recursiveFk (const JntArray & q_in, const SegmentMap::const_iterator & it) private
References KDL::Tree::getRootSegment(), GetTreeElementParent, GetTreeElementQNr, GetTreeElementSegment, recursiveFk(), and tree.
Referenced by JntToCart(), and recursiveFk().
Member Data Documentation
tree
const Tree KDL::TreeFkSolverPos_recursive::tree private
Referenced by JntToCart(), and recursiveFk().
The documentation for this class was generated from the following files:
src/treefksolverpos_recursive.hpp
src/treefksolverpos_recursive.cpp