KDL: KDL::Joint Class Reference
KDL::Joint Class Reference
Kinematic Families
#include <src/joint.hpp>
Classes
class joint_type_exception
Public Types
enum JointType {
RotAxis , RotX , RotY , RotZ ,
TransAxis , TransX , TransY , TransZ ,
Fixed , None =Fixed
}
Public Member Functions
Joint (const std::string &name, const JointType &type=Fixed, const double &scale=1, const double &offset=0, const double &inertia=0, const double &damping=0, const double &stiffness=0)
Constructor of a joint.
Joint (const JointType &type=Fixed, const double &scale=1, const double &offset=0, const double &inertia=0, const double &damping=0, const double &stiffness=0)
Constructor of a joint.
Joint (const std::string &name, const Vector &_origin, const Vector &_axis, const JointType &type, const double &_scale=1, const double &_offset=0, const double &_inertia=0, const double &_damping=0, const double &_stiffness=0)
Constructor of a joint.
Joint (const Vector &_origin, const Vector &_axis, const JointType &type, const double &_scale=1, const double &_offset=0, const double &_inertia=0, const double &_damping=0, const double &_stiffness=0)
Constructor of a joint.
Frame pose (const double &q) const
Request the 6D-pose between the beginning and the end of the joint at joint position q.
Twist twist (const double &qdot) const
Request the resulting 6D-velocity with a joint velocity qdot.
Vector JointAxis () const
Request the Vector corresponding to the axis of a revolute joint.
Vector JointOrigin () const
Request the Vector corresponding to the origin of a revolute joint.
const std::string & getName () const
Request the name of the joint.
const JointType & getType () const
Request the type of the joint.
const std::string getTypeName () const
Request the stringified type of the joint.
const double & getScale () const
Request the scale of the joint.
const double & getOffset () const
Request the offset of the joint.
const double & getInertia () const
Request the inertia of the joint.
const double & getDamping () const
Request the damping of the joint.
const double & getStiffness () const
Request the stiffness of the joint.
const Vector & getAxis () const
Request the axis of the joint.
const Vector & getOrigin () const
Request the origin of the joint.
virtual ~Joint ()
Private Attributes
std::string name
Joint::JointType type
double scale
double offset
double inertia
double damping
double stiffness
Vector axis
Vector origin
Frame joint_pose
double q_previous
KDL::Joint::joint_type_exception joint_type_ex
Detailed Description
 \brief This class encapsulates a simple joint, that is with one
 parameterized degree of freedom and with scalar dynamic properties.
A simple joint is described by the following properties :
scale: ratio between motion input and motion output
offset: between the "physical" and the "logical" zero position.
type: revolute or translational, along one of the basic frame axes
inertia, stiffness and damping: scalars representing the physical effects along/about the joint axis only.
Member Enumeration Documentation
JointType
enum KDL::Joint::JointType
Enumerator
RotAxis
RotX
RotY
RotZ
TransAxis
TransX
TransY
TransZ
Fixed
None
Constructor & Destructor Documentation
Joint() [1/4]
KDL::Joint::Joint (const std::string & name, const JointType & type = Fixed, const double & scale = 1, const double & offset = 0, const double & inertia = 0, const double & damping = 0, const double & stiffness = 0) explicit
Constructor of a joint.
Parameters
name of the joint
type type of the joint, default: Joint::Fixed
scale scale between joint input and actual geometric movement, default: 1
offset offset between joint input and actual geometric input, default: 0
inertia 1D inertia along the joint axis, default: 0
damping 1D damping along the joint axis, default: 0
stiffness 1D stiffness along the joint axis, default: 0
References joint_type_ex, RotAxis, TransAxis, and type.
Joint() [2/4]
KDL::Joint::Joint (const JointType & type = Fixed, const double & scale = 1, const double & offset = 0, const double & inertia = 0, const double & damping = 0, const double & stiffness = 0) explicit
Constructor of a joint.
Parameters
type type of the joint, default: Joint::Fixed
scale scale between joint input and actual geometric movement, default: 1
offset offset between joint input and actual geometric input, default: 0
inertia 1D inertia along the joint axis, default: 0
damping 1D damping along the joint axis, default: 0
stiffness 1D stiffness along the joint axis, default: 0
References joint_type_ex, RotAxis, TransAxis, and type.
Joint() [3/4]
KDL::Joint::Joint (const std::string & name, const Vector & _origin, const Vector & _axis, const JointType & type, const double & _scale = 1, const double & _offset = 0, const double & _inertia = 0, const double & _damping = 0, const double & _stiffness = 0)
Constructor of a joint.
Parameters
name of the joint
origin the origin of the joint
axis the axis of the joint
scale scale between joint input and actual geometric movement, default: 1
offset offset between joint input and actual geometric input, default: 0
inertia 1D inertia along the joint axis, default: 0
damping 1D damping along the joint axis, default: 0
stiffness 1D stiffness along the joint axis, default: 0
References joint_type_ex, RotAxis, TransAxis, and type.
Joint() [4/4]
KDL::Joint::Joint (const Vector & _origin, const Vector & _axis, const JointType & type, const double & _scale = 1, const double & _offset = 0, const double & _inertia = 0, const double & _damping = 0, const double & _stiffness = 0)
Constructor of a joint.
Parameters
origin the origin of the joint
axis the axis of the joint
scale scale between joint input and actual geometric movement, default: 1
offset offset between joint input and actual geometric input, default: 0
inertia 1D inertia along the joint axis, default: 0
damping 1D damping along the joint axis, default: 0
stiffness 1D stiffness along the joint axis, default: 0
References joint_type_ex, RotAxis, TransAxis, and type.
~Joint()
KDL::Joint::~Joint () virtual
Member Function Documentation
getAxis()
const Vector & KDL::Joint::getAxis () const inline
Request the axis of the joint.
Returns
const reference to the axis of the joint
References axis.
getDamping()
const double & KDL::Joint::getDamping () const inline
Request the damping of the joint.
Returns
const reference to the damping of the joint
References damping.
getInertia()
const double & KDL::Joint::getInertia () const inline
Request the inertia of the joint.
Returns
const reference to the inertia of the joint
References inertia.
Referenced by KDL::ChainIdSolver_RNE::CartToJnt(), KDL::ChainHdSolver_Vereshchagin::downwards_sweep(), KDL::ChainDynParam::JntToMass(), and KDL::TreeIdSolver_RNE::rne_step().
getName()
const std::string & KDL::Joint::getName () const inline
Request the name of the joint.
Returns
const reference to the name of the joint
References name.
Referenced by KDL::Tree::getChain(), and KDL::operator<<().
getOffset()
const double & KDL::Joint::getOffset () const inline
Request the offset of the joint.
Returns
const reference to the offset of the joint
References offset.
getOrigin()
const Vector & KDL::Joint::getOrigin () const inline
Request the origin of the joint.
Returns
const reference to the origin of the joint
References origin.
getScale()
const double & KDL::Joint::getScale () const inline
Request the scale of the joint.
Returns
const reference to the scale of the joint
References scale.
getStiffness()
const double & KDL::Joint::getStiffness () const inline
Request the stiffness of the joint.
Returns
const reference to the stiffness of the joint
References stiffness.
getType()
const JointType & KDL::Joint::getType () const inline
Request the type of the joint.
Returns
const reference to the type
References type.
Referenced by KDL::Chain::addSegment(), KDL::Tree::addSegment(), KDL::ChainIdSolver_RNE::CartToJnt(), KDL::ChainIkSolverPos_LMA::compute_fwdpos(), KDL::ChainIkSolverPos_LMA::compute_jacobian(), KDL::ChainHdSolver_Vereshchagin::downwards_sweep(), KDL::ChainHdSolver_Vereshchagin::final_upwards_sweep(), KDL::Tree::getChain(), KDL::ChainHdSolver_Vereshchagin::initial_upwards_sweep(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainJntToJacSolver::JntToJac(), KDL::ChainJntToJacDotSolver::JntToJacDot(), KDL::ChainDynParam::JntToMass(), and KDL::TreeIdSolver_RNE::rne_step().
getTypeName()
const std::string KDL::Joint::getTypeName () const inline
Request the stringified type of the joint.
Returns
const string
References Fixed, RotAxis, RotX, RotY, RotZ, TransAxis, TransX, TransY, TransZ, and type.
Referenced by KDL::operator<<().
JointAxis()
Vector KDL::Joint::JointAxis () const
Request the Vector corresponding to the axis of a revolute joint.
Returns
Vector. e.g (1,0,0) for RotX etc.
References axis, Fixed, RotAxis, RotX, RotY, RotZ, TransAxis, TransX, TransY, TransZ, type, and KDL::Vector::Zero().
Referenced by KDL::Tree::getChain(), and KDL::operator<<().
JointOrigin()
Vector KDL::Joint::JointOrigin () const
Request the Vector corresponding to the origin of a revolute joint.
Returns
Vector
References origin.
Referenced by KDL::Tree::getChain(), and KDL::operator<<().
pose()
Frame KDL::Joint::pose (const double & q) const
Request the 6D-pose between the beginning and the end of the joint at joint position q.
Parameters
q the 1D joint position
Returns
the resulting 6D-pose
References axis, Fixed, KDL::Frame::Identity(), offset, origin, KDL::Rotation::Rot2(), RotAxis, KDL::Rotation::RotX(), RotX, KDL::Rotation::RotY(), RotY, KDL::Rotation::RotZ(), RotZ, scale, TransAxis, TransX, TransY, TransZ, and type.
Referenced by KDL::Segment::getFrameToTip(), KDL::Segment::pose(), KDL::Segment::setFrameToTip(), and KDL::Segment::twist().
twist()
Twist KDL::Joint::twist (const double & qdot) const
Request the resulting 6D-velocity with a joint velocity qdot.
Parameters
qdot the 1D joint velocity
Returns
the resulting 6D-velocity
References axis, Fixed, RotAxis, RotX, RotY, RotZ, scale, TransAxis, TransX, TransY, TransZ, type, and KDL::Twist::Zero().
Referenced by KDL::Segment::twist().
Member Data Documentation
axis
Vector KDL::Joint::axis private
Referenced by getAxis(), JointAxis(), pose(), and twist().
damping
double KDL::Joint::damping private
Referenced by getDamping().
inertia
double KDL::Joint::inertia private
Referenced by getInertia().
joint_pose
Frame KDL::Joint::joint_pose mutable private
joint_type_ex
KDL::Joint::joint_type_exception KDL::Joint::joint_type_ex private
Referenced by Joint(), Joint(), Joint(), and Joint().
name
std::string KDL::Joint::name private
Referenced by getName().
offset
double KDL::Joint::offset private
Referenced by getOffset(), and pose().
origin
Vector KDL::Joint::origin private
Referenced by getOrigin(), JointOrigin(), and pose().
q_previous
double KDL::Joint::q_previous mutable private
scale
double KDL::Joint::scale private
Referenced by getScale(), pose(), and twist().
stiffness
double KDL::Joint::stiffness private
Referenced by getStiffness().
type
Joint::JointType KDL::Joint::type private
Referenced by getType(), getTypeName(), Joint(), Joint(), Joint(), Joint(), JointAxis(), pose(), and twist().
The documentation for this class was generated from the following files:
src/joint.hpp
src/joint.cpp