KDL: KDL::Chain Class Reference
KDL::Chain Class Reference
Kinematic Families
#include <src/chain.hpp>
Public Member Functions
Chain ()
The constructor of a chain, a new chain is always empty.
Chain (const Chain &in)
Chain & operator= (const Chain &arg)
void addSegment (const Segment &segment)
Adds a new segment to the end of the chain.
void addChain (const Chain &chain)
Adds a complete chain to the end of the chain The added chain is copied.
unsigned int getNrOfJoints () const
Request the total number of joints in the chain.
unsigned int getNrOfSegments () const
Request the total number of segments in the chain.
const Segment & getSegment (unsigned int nr) const
Request the nr'd segment of the chain.
Segment & getSegment (unsigned int nr)
Request the nr'd segment of the chain.
virtual ~Chain ()
Public Attributes
std::vector< Segment > segments
Private Attributes
unsigned int nrOfJoints
unsigned int nrOfSegments
Detailed Description
 \brief This class encapsulates a <strong>serial</strong> kinematic
 interconnection structure. It is built out of segments.
Constructor & Destructor Documentation
Chain() [1/2]
KDL::Chain::Chain ()
The constructor of a chain, a new chain is always empty.
Chain() [2/2]
KDL::Chain::Chain (const Chain & in)
References addSegment(), getNrOfSegments(), and getSegment().
~Chain()
KDL::Chain::~Chain () virtual
Member Function Documentation
addChain()
void KDL::Chain::addChain (const Chain & chain)
Adds a complete chain to the end of the chain The added chain is copied.
Parameters
chain The chain to add
References addSegment(), getNrOfSegments(), and getSegment().
addSegment()
void KDL::Chain::addSegment (const Segment & segment)
Adds a new segment to the end of the chain.
Parameters
segment The segment to add
References KDL::Joint::Fixed, KDL::Segment::getJoint(), KDL::Joint::getType(), nrOfJoints, nrOfSegments, and segments.
Referenced by addChain(), Chain(), KDL::Tree::getChain(), and operator=().
getNrOfJoints()
unsigned int KDL::Chain::getNrOfJoints () const inline
Request the total number of joints in the chain.
Important: It is not the same as the total number of segments since a segment does not need to have a joint. This function is important when creating a KDL::JntArray to use with this chain.
Returns
total nr of joints
References nrOfJoints.
Referenced by KDL::ChainIdSolver_RNE::CartToJnt(), KDL::ChainFdSolver_RNE::CartToJnt(), KDL::ChainHdSolver_Vereshchagin::CartToJnt(), KDL::ChainIkSolverVel_pinv::CartToJnt(), KDL::ChainIkSolverVel_pinv_givens::CartToJnt(), KDL::ChainIkSolverVel_pinv_nso::CartToJnt(), KDL::ChainIkSolverVel_wdls::CartToJnt(), KDL::ChainIkSolverPos_NR::CartToJnt(), KDL::ChainIkSolverPos_NR_JL::CartToJnt(), KDL::ChainIkSolverPos_LMA::CartToJnt(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainExternalWrenchEstimator::JntToExtWrench(), KDL::ChainJntToJacSolver::JntToJac(), KDL::ChainJntToJacDotSolver::JntToJacDot(), KDL::ChainDynParam::JntToMass(), KDL::ChainJntToJacSolver::setLockedJoints(), KDL::ChainIkSolverVel_wdls::setWeightJS(), KDL::ChainDynParam::updateInternalDataStructures(), KDL::ChainExternalWrenchEstimator::updateInternalDataStructures(), KDL::ChainFdSolver_RNE::updateInternalDataStructures(), KDL::ChainHdSolver_Vereshchagin::updateInternalDataStructures(), KDL::ChainIdSolver_RNE::updateInternalDataStructures(), KDL::ChainIkSolverPos_LMA::updateInternalDataStructures(), KDL::ChainIkSolverPos_NR::updateInternalDataStructures(), KDL::ChainIkSolverPos_NR_JL::updateInternalDataStructures(), KDL::ChainIkSolverVel_pinv::updateInternalDataStructures(), KDL::ChainIkSolverVel_pinv_givens::updateInternalDataStructures(), KDL::ChainIkSolverVel_pinv_nso::updateInternalDataStructures(), KDL::ChainIkSolverVel_wdls::updateInternalDataStructures(), KDL::ChainJntToJacDotSolver::updateInternalDataStructures(), and KDL::ChainJntToJacSolver::updateInternalDataStructures().
getNrOfSegments()
unsigned int KDL::Chain::getNrOfSegments () const inline
Request the total number of segments in the chain.
Returns
total number of segments
References nrOfSegments.
Referenced by addChain(), KDL::Tree::addChain(), KDL::ChainIdSolver_RNE::CartToJnt(), KDL::ChainFdSolver_RNE::CartToJnt(), KDL::ChainHdSolver_Vereshchagin::CartToJnt(), Chain(), KDL::ChainIkSolverPos_LMA::compute_fwdpos(), KDL::ChainIkSolverPos_LMA::compute_jacobian(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainExternalWrenchEstimator::JntToExtWrench(), KDL::ChainJntToJacSolver::JntToJac(), KDL::ChainJntToJacDotSolver::JntToJacDot(), KDL::ChainDynParam::JntToMass(), KDL::operator<<(), KDL::ChainDynParam::updateInternalDataStructures(), KDL::ChainExternalWrenchEstimator::updateInternalDataStructures(), KDL::ChainFdSolver_RNE::updateInternalDataStructures(), KDL::ChainHdSolver_Vereshchagin::updateInternalDataStructures(), KDL::ChainIdSolver_RNE::updateInternalDataStructures(), and KDL::ChainIkSolverPos_LMA::updateInternalDataStructures().
getSegment() [1/2]
Segment & KDL::Chain::getSegment (unsigned int nr)
Request the nr'd segment of the chain.
There is no boundary checking.
Parameters
nr the nr of the segment starting from 0
Returns
a reference to the nr'd segment
References segments.
getSegment() [2/2]
const Segment & KDL::Chain::getSegment (unsigned int nr) const
Request the nr'd segment of the chain.
There is no boundary checking.
Parameters
nr the nr of the segment starting from 0
Returns
a constant reference to the nr'd segment
References segments.
Referenced by addChain(), KDL::Tree::addChain(), KDL::ChainIdSolver_RNE::CartToJnt(), Chain(), KDL::ChainIkSolverPos_LMA::compute_fwdpos(), KDL::ChainIkSolverPos_LMA::compute_jacobian(), KDL::ChainHdSolver_Vereshchagin::downwards_sweep(), KDL::ChainHdSolver_Vereshchagin::final_upwards_sweep(), KDL::ChainHdSolver_Vereshchagin::initial_upwards_sweep(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainJntToJacSolver::JntToJac(), KDL::ChainJntToJacDotSolver::JntToJacDot(), KDL::ChainDynParam::JntToMass(), KDL::operator<<(), and operator=().
operator=()
Chain & KDL::Chain::operator= (const Chain & arg)
References addSegment(), getSegment(), nrOfJoints, nrOfSegments, and segments.
Member Data Documentation
nrOfJoints
unsigned int KDL::Chain::nrOfJoints private
Referenced by addSegment(), getNrOfJoints(), and operator=().
nrOfSegments
unsigned int KDL::Chain::nrOfSegments private
Referenced by addSegment(), getNrOfSegments(), and operator=().
segments
std::vector<Segment> KDL::Chain::segments
Referenced by addSegment(), getSegment(), getSegment(), and operator=().
The documentation for this class was generated from the following files:
src/chain.hpp
src/chain.cpp