KDL: KDL::ChainJntToJacDotSolver Class Reference
KDL::ChainJntToJacDotSolver Class Reference
Computes the Jacobian time derivative (Jdot) by calculating the partial derivatives regarding to a joint angle, in the Hybrid, Body-fixed or Inertial representation.
#include <src/chainjnttojacdotsolver.hpp>
Public Types
enum {
E_DEGRADED = +1 , E_NOERROR = 0 , E_NO_CONVERGE = -1 , E_UNDEFINED = -2 ,
E_NOT_UP_TO_DATE = -3 , E_SIZE_MISMATCH = -4 , E_MAX_ITERATIONS_EXCEEDED = -5 , E_OUT_OF_RANGE = -6 ,
E_NOT_IMPLEMENTED = -7 , E_SVD_FAILED = -8
}
Public Member Functions
ChainJntToJacDotSolver (const Chain &chain)
virtual ~ChainJntToJacDotSolver ()
virtual int JntToJacDot (const KDL::JntArrayVel &q_in, KDL::Twist &jac_dot_q_dot, int seg_nr=-1)
Computes \({}_{bs}\dot{J}^{ee}.\dot{q} \).
virtual int JntToJacDot (const KDL::JntArrayVel &q_in, KDL::Jacobian &jdot, int seg_nr=-1)
Computes \({}_{bs}\dot{J}^{ee} \).
int setLockedJoints (const std::vector< bool > &locked_joints)
void setHybridRepresentation ()
JntToJacDot() will compute in the Hybrid representation (ref Frame: base, ref Point: end-effector)
void setBodyFixedRepresentation ()
JntToJacDot() will compute in the Body-fixed representation (ref Frame: end-effector, ref Point: end-effector)
void setInertialRepresentation ()
JntToJacDot() will compute in the Inertial representation (ref Frame: base, ref Point: base)
void setRepresentation (const int &representation)
Sets the internal variable for the representation (with a check on the value)
virtual void updateInternalDataStructures ()
Update the internal data structures.
virtual const char * strError (const int error) const
Return a description of the latest error.
virtual int getError () const
Return the latest error.
Static Public Attributes
static const int E_JAC_DOT_FAILED = -100
static const int E_JACSOLVER_FAILED = -101
static const int E_FKSOLVERPOS_FAILED = -102
static const int HYBRID = 0
static const int BODYFIXED = 1
static const int INERTIAL = 2
Protected Member Functions
const Twist & getPartialDerivativeHybrid (const Jacobian &bs_J_ee, const unsigned int &joint_idx, const unsigned int &column_idx)
Computes \(\frac{\partial {}_{bs}J^{i,ee}}{\partial q^{j}}.\dot{q}^{j} \).
const Twist & getPartialDerivativeBodyFixed (const Jacobian &ee_J_ee, const unsigned int &joint_idx, const unsigned int &column_idx)
Computes \(\frac{\partial {}_{ee}J^{i,ee}}{\partial q^{j}}.\dot{q}^{j} \).
const Twist & getPartialDerivativeInertial (const Jacobian &bs_J_bs, const unsigned int &joint_idx, const unsigned int &column_idx)
Computes \(\frac{\partial {}_{bs}J^{i,bs}}{\partial q^{j}}.\dot{q}^{j} \).
const Twist & getPartialDerivative (const Jacobian &J, const unsigned int &joint_idx, const unsigned int &column_idx, const int &representation)
Computes \(\frac{\partial J^{i,ee}}{\partial q^{j}}.\dot{q}^{j} \).
Protected Attributes
int error
Latest error, initialized to E_NOERROR in constructor.
Private Attributes
const Chain & chain
std::vector< bool > locked_joints_
unsigned int nr_of_unlocked_joints_
ChainJntToJacSolver jac_solver_
Jacobian jac_
Jacobian jac_dot_
int representation_
ChainFkSolverPos_recursive fk_solver_
Frame F_bs_ee_
Twist jac_dot_k_
Twist jac_j_
Twist jac_i_
Twist t_djdq_
Detailed Description
Computes the Jacobian time derivative (Jdot) by calculating the partial derivatives regarding to a joint angle, in the Hybrid, Body-fixed or Inertial representation.
This work is based on : Symbolic differentiation of the velocity mapping for a serial kinematic chain H. Bruyninckx, J. De Schutter doi:10.1016/0094-114X(95)00069-B
url : http://www.sciencedirect.com/science/article/pii/0094114X9500069B
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
Enumerator
E_DEGRADED
Converged but degraded solution (e.g. WDLS with psuedo-inverse singular)
E_NOERROR
No error.
E_NO_CONVERGE
Failed to converge.
E_UNDEFINED
Undefined value (e.g. computed a NAN, or tan(90 degrees))
E_NOT_UP_TO_DATE
Chain size changed.
E_SIZE_MISMATCH
Input size does not match internal state.
E_MAX_ITERATIONS_EXCEEDED
Maximum number of iterations exceeded.
E_OUT_OF_RANGE
Requested index out of range.
E_NOT_IMPLEMENTED
Not yet implemented.
E_SVD_FAILED
Internal svd calculation failed.
Constructor & Destructor Documentation
ChainJntToJacDotSolver()
KDL::ChainJntToJacDotSolver::ChainJntToJacDotSolver (const Chain & chain) explicit
~ChainJntToJacDotSolver()
KDL::ChainJntToJacDotSolver::~ChainJntToJacDotSolver () virtual
Member Function Documentation
getError()
virtual int KDL::SolverI::getError () const inline virtual inherited
Return the latest error.
References KDL::SolverI::error.
getPartialDerivative()
const Twist & KDL::ChainJntToJacDotSolver::getPartialDerivative (const Jacobian & J, const unsigned int & joint_idx, const unsigned int & column_idx, const int & representation) protected
Computes \(\frac{\partial J^{i,ee}}{\partial q^{j}}.\dot{q}^{j} \).
Parameters
bs_J_bs The Jacobian expressed in the base frame with the end effector as the reference point
joint_idx The indice of the current joint (j in the formula)
column_idx The indice of the current column (i in the formula)
representation The representation (Hybrid,Body-fixed,Inertial) in which you want to get dJ/dqj .qdotj
Returns
Twist The twist representing dJi/dqj .qdotj
References BODYFIXED, getPartialDerivativeBodyFixed(), getPartialDerivativeHybrid(), getPartialDerivativeInertial(), HYBRID, INERTIAL, KDL::SetToZero(), and t_djdq_.
Referenced by JntToJacDot().
getPartialDerivativeBodyFixed()
const Twist & KDL::ChainJntToJacDotSolver::getPartialDerivativeBodyFixed (const Jacobian & ee_J_ee, const unsigned int & joint_idx, const unsigned int & column_idx) protected
Computes \(\frac{\partial {}_{ee}J^{i,ee}}{\partial q^{j}}.\dot{q}^{j} \).
Parameters
bs_J_ee The Jacobian expressed in the end effector frame with the end effector as the reference point
joint_idx The indice of the current joint (j in the formula)
column_idx The indice of the current column (i in the formula)
Returns
Twist The twist representing dJi/dqj .qdotj
References KDL::Jacobian::getColumn(), jac_i_, jac_j_, KDL::Twist::rot, KDL::SetToZero(), t_djdq_, and KDL::Twist::vel.
Referenced by getPartialDerivative().
getPartialDerivativeHybrid()
const Twist & KDL::ChainJntToJacDotSolver::getPartialDerivativeHybrid (const Jacobian & bs_J_ee, const unsigned int & joint_idx, const unsigned int & column_idx) protected
Computes \(\frac{\partial {}_{bs}J^{i,ee}}{\partial q^{j}}.\dot{q}^{j} \).
Parameters
bs_J_ee The Jacobian expressed in the base frame with the end effector as the reference point (default in KDL Jacobian Solver)
joint_idx The index of the current joint (j in the formula)
column_idx The index of the current column (i in the formula)
Returns
Twist The twist representing dJi/dqj .qdotj
References KDL::Jacobian::getColumn(), jac_i_, jac_j_, KDL::Twist::rot, KDL::SetToZero(), t_djdq_, and KDL::Twist::vel.
Referenced by getPartialDerivative().
getPartialDerivativeInertial()
const Twist & KDL::ChainJntToJacDotSolver::getPartialDerivativeInertial (const Jacobian & bs_J_bs, const unsigned int & joint_idx, const unsigned int & column_idx) protected
Computes \(\frac{\partial {}_{bs}J^{i,bs}}{\partial q^{j}}.\dot{q}^{j} \).
Parameters
ee_J_ee The Jacobian expressed in the base frame with the base as the reference point
joint_idx The indice of the current joint (j in the formula)
column_idx The indice of the current column (i in the formula)
Returns
Twist The twist representing dJi/dqj .qdotj
References KDL::Jacobian::getColumn(), jac_i_, jac_j_, KDL::Twist::rot, KDL::SetToZero(), t_djdq_, and KDL::Twist::vel.
Referenced by getPartialDerivative().
JntToJacDot() [1/2]
int KDL::ChainJntToJacDotSolver::JntToJacDot (const KDL::JntArrayVel & q_in, KDL::Jacobian & jdot, int seg_nr = -1) virtual
Computes \({}_{bs}\dot{J}^{ee} \).
Parameters
q_in Current joint positions and velocities
jdot The jacobian time derivative in the configured representation (HYBRID, BODYFIXED or INERTIAL)
seg_nr The final segment to compute
Returns
int 0 if no errors happened
References BODYFIXED, chain, KDL::Jacobian::changeBase, KDL::Jacobian::changeRefPoint, KDL::Jacobian::columns(), E_FKSOLVERPOS_FAILED, E_JAC_DOT_FAILED, E_JACSOLVER_FAILED, KDL::SolverI::E_NOERROR, KDL::SolverI::E_NOT_UP_TO_DATE, KDL::SolverI::E_OUT_OF_RANGE, KDL::SolverI::E_SIZE_MISMATCH, KDL::SolverI::error, F_bs_ee_, KDL::Joint::Fixed, fk_solver_, KDL::Segment::getJoint(), KDL::Chain::getNrOfJoints(), KDL::Chain::getNrOfSegments(), getPartialDerivative(), KDL::Chain::getSegment(), KDL::Joint::getType(), HYBRID, INERTIAL, KDL::Rotation::Inverse(), jac_, jac_dot_k_, jac_solver_, KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainJntToJacSolver::JntToJac(), locked_joints_, KDL::Frame::M, nr_of_unlocked_joints_, KDL::Frame::p, KDL::JntArrayVel::q, KDL::JntArrayVel::qdot, representation_, KDL::JntArray::rows(), KDL::Jacobian::setColumn(), and KDL::SetToZero().
JntToJacDot() [2/2]
int KDL::ChainJntToJacDotSolver::JntToJacDot (const KDL::JntArrayVel & q_in, KDL::Twist & jac_dot_q_dot, int seg_nr = -1) virtual
Computes \({}_{bs}\dot{J}^{ee}.\dot{q} \).
Parameters
q_in Current joint positions and velocities
jac_dot_q_dot The twist representing Jdot*qdot
seg_nr The final segment to compute
Returns
int 0 if no errors happened
References KDL::SolverI::E_NOERROR, KDL::SolverI::error, jac_dot_, JntToJacDot(), KDL::MultiplyJacobian(), and KDL::JntArrayVel::qdot.
Referenced by JntToJacDot().
setBodyFixedRepresentation()
void KDL::ChainJntToJacDotSolver::setBodyFixedRepresentation () inline
JntToJacDot() will compute in the Body-fixed representation (ref Frame: end-effector, ref Point: end-effector)
Returns
void
References BODYFIXED, and setRepresentation().
setHybridRepresentation()
void KDL::ChainJntToJacDotSolver::setHybridRepresentation () inline
JntToJacDot() will compute in the Hybrid representation (ref Frame: base, ref Point: end-effector)
Returns
void
References HYBRID, and setRepresentation().
setInertialRepresentation()
void KDL::ChainJntToJacDotSolver::setInertialRepresentation () inline
JntToJacDot() will compute in the Inertial representation (ref Frame: base, ref Point: base)
Returns
void
References INERTIAL, and setRepresentation().
setLockedJoints()
int KDL::ChainJntToJacDotSolver::setLockedJoints (const std::vector< bool > & locked_joints)
References KDL::SolverI::E_NOERROR, KDL::SolverI::E_SIZE_MISMATCH, KDL::SolverI::error, locked_joints_, and nr_of_unlocked_joints_.
Referenced by updateInternalDataStructures().
setRepresentation()
void KDL::ChainJntToJacDotSolver::setRepresentation (const int & representation)
Sets the internal variable for the representation (with a check on the value)
Parameters
representation The representation for Jdot : HYBRID,BODYFIXED or INERTIAL
Returns
void
References BODYFIXED, HYBRID, INERTIAL, and representation_.
Referenced by setBodyFixedRepresentation(), setHybridRepresentation(), and setInertialRepresentation().
strError()
const char * KDL::ChainJntToJacDotSolver::strError (const int error) const virtual
Return a description of the latest error.
Returns
if error is known then a description of error, otherwise "UNKNOWN ERROR"
Reimplemented from KDL::SolverI.
References E_FKSOLVERPOS_FAILED, E_JAC_DOT_FAILED, E_JACSOLVER_FAILED, KDL::SolverI::error, and KDL::SolverI::strError().
updateInternalDataStructures()
void KDL::ChainJntToJacDotSolver::updateInternalDataStructures () virtual
Update the internal data structures.
This is required if the number of segments or number of joints of a chain/tree have changed. This provides a single point of contact for solver memory allocations.
Implements KDL::SolverI.
References chain, fk_solver_, KDL::Chain::getNrOfJoints(), jac_, jac_dot_, jac_solver_, locked_joints_, KDL::Jacobian::resize(), setLockedJoints(), KDL::ChainFkSolverPos_recursive::updateInternalDataStructures(), and KDL::ChainJntToJacSolver::updateInternalDataStructures().
Member Data Documentation
BODYFIXED
const int KDL::ChainJntToJacDotSolver::BODYFIXED = 1 static
Referenced by getPartialDerivative(), JntToJacDot(), setBodyFixedRepresentation(), and setRepresentation().
chain
const Chain& KDL::ChainJntToJacDotSolver::chain private
Referenced by JntToJacDot(), and updateInternalDataStructures().
E_FKSOLVERPOS_FAILED
const int KDL::ChainJntToJacDotSolver::E_FKSOLVERPOS_FAILED = -102 static
Referenced by JntToJacDot(), and strError().
E_JAC_DOT_FAILED
const int KDL::ChainJntToJacDotSolver::E_JAC_DOT_FAILED = -100 static
Referenced by JntToJacDot(), and strError().
E_JACSOLVER_FAILED
const int KDL::ChainJntToJacDotSolver::E_JACSOLVER_FAILED = -101 static
Referenced by JntToJacDot(), and strError().
error
int KDL::SolverI::error protected inherited
Latest error, initialized to E_NOERROR in constructor.
Referenced by KDL::ChainIkSolverVel_pinv::CartToJnt(), KDL::ChainIkSolverVel_pinv_givens::CartToJnt(), KDL::ChainIkSolverVel_pinv_nso::CartToJnt(), KDL::ChainIdSolver_RNE::CartToJnt(), KDL::TreeIdSolver_RNE::CartToJnt(), KDL::ChainFdSolver_RNE::CartToJnt(), KDL::ChainHdSolver_Vereshchagin::CartToJnt(), KDL::ChainIkSolverVel_pinv::CartToJnt(), KDL::ChainIkSolverVel_pinv_givens::CartToJnt(), KDL::ChainIkSolverVel_pinv_nso::CartToJnt(), KDL::ChainIkSolverVel_wdls::CartToJnt(), KDL::ChainIkSolverPos_NR::CartToJnt(), KDL::ChainIkSolverPos_NR_JL::CartToJnt(), KDL::ChainIkSolverPos_LMA::CartToJnt(), KDL::SolverI::getError(), KDL::ChainIkSolverVel_wdls::getSigma(), KDL::ChainFkSolverPos_recursive::JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainExternalWrenchEstimator::JntToExtWrench(), KDL::ChainJntToJacSolver::JntToJac(), JntToJacDot(), JntToJacDot(), KDL::ChainDynParam::JntToMass(), KDL::ChainExternalWrenchEstimator::setInitialMomentum(), KDL::ChainIkSolverPos_NR_JL::setJointLimits(), setLockedJoints(), KDL::ChainJntToJacSolver::setLockedJoints(), KDL::ChainIkSolverVel_pinv_nso::setOptPos(), KDL::ChainIkSolverVel_wdls::setWeightJS(), KDL::ChainIkSolverVel_pinv_nso::setWeights(), KDL::ChainIkSolverVel_wdls::setWeightTS(), KDL::ChainExternalWrenchEstimator::strError(), KDL::ChainIkSolverPos_LMA::strError(), KDL::ChainIkSolverPos_NR::strError(), KDL::ChainIkSolverPos_NR_JL::strError(), KDL::ChainIkSolverVel_pinv::strError(), KDL::ChainIkSolverVel_wdls::strError(), strError(), and KDL::SolverI::strError().
F_bs_ee_
Frame KDL::ChainJntToJacDotSolver::F_bs_ee_ private
Referenced by JntToJacDot().
fk_solver_
ChainFkSolverPos_recursive KDL::ChainJntToJacDotSolver::fk_solver_ private
Referenced by JntToJacDot(), and updateInternalDataStructures().
HYBRID
const int KDL::ChainJntToJacDotSolver::HYBRID = 0 static
Referenced by getPartialDerivative(), JntToJacDot(), setHybridRepresentation(), and setRepresentation().
INERTIAL
const int KDL::ChainJntToJacDotSolver::INERTIAL = 2 static
Referenced by getPartialDerivative(), JntToJacDot(), setInertialRepresentation(), and setRepresentation().
jac_
Jacobian KDL::ChainJntToJacDotSolver::jac_ private
Referenced by JntToJacDot(), and updateInternalDataStructures().
jac_dot_
Jacobian KDL::ChainJntToJacDotSolver::jac_dot_ private
Referenced by JntToJacDot(), and updateInternalDataStructures().
jac_dot_k_
Twist KDL::ChainJntToJacDotSolver::jac_dot_k_ private
Referenced by JntToJacDot().
jac_i_
Twist KDL::ChainJntToJacDotSolver::jac_i_ private
Referenced by getPartialDerivativeBodyFixed(), getPartialDerivativeHybrid(), and getPartialDerivativeInertial().
jac_j_
Twist KDL::ChainJntToJacDotSolver::jac_j_ private
Referenced by getPartialDerivativeBodyFixed(), getPartialDerivativeHybrid(), and getPartialDerivativeInertial().
jac_solver_
ChainJntToJacSolver KDL::ChainJntToJacDotSolver::jac_solver_ private
Referenced by JntToJacDot(), and updateInternalDataStructures().
locked_joints_
std::vector<bool> KDL::ChainJntToJacDotSolver::locked_joints_ private
Referenced by JntToJacDot(), setLockedJoints(), and updateInternalDataStructures().
nr_of_unlocked_joints_
unsigned int KDL::ChainJntToJacDotSolver::nr_of_unlocked_joints_ private
Referenced by JntToJacDot(), and setLockedJoints().
representation_
int KDL::ChainJntToJacDotSolver::representation_ private
Referenced by JntToJacDot(), and setRepresentation().
t_djdq_
Twist KDL::ChainJntToJacDotSolver::t_djdq_ private
Referenced by getPartialDerivative(), getPartialDerivativeBodyFixed(), getPartialDerivativeHybrid(), and getPartialDerivativeInertial().
The documentation for this class was generated from the following files:
src/chainjnttojacdotsolver.hpp
src/chainjnttojacdotsolver.cpp