KDL: KDL::TreeElement Class Reference
KDL::TreeElement Class Reference
#include <src/tree.hpp>
Public Member Functions
TreeElement (const Segment &segment_in, const SegmentMap::const_iterator &parent_in, unsigned int q_nr_in)
Static Public Member Functions
static TreeElementType Root (const std::string &root_name)
Public Attributes
Segment segment
unsigned int q_nr
SegmentMap::const_iterator parent
std::vector< SegmentMap::const_iterator > children
Private Member Functions
TreeElement (const std::string &name)
Constructor & Destructor Documentation
TreeElement() [1/2]
KDL::TreeElement::TreeElement (const Segment & segment_in, const SegmentMap::const_iterator & parent_in, unsigned int q_nr_in) inline
TreeElement() [2/2]
KDL::TreeElement::TreeElement (const std::string & name) inline private
Member Function Documentation
Root()
static TreeElementType KDL::TreeElement::Root (const std::string & root_name) inline static
Referenced by KDL::Tree::operator=(), KDL::Tree::Tree(), and KDL::Tree::Tree().
Member Data Documentation
children
std::vector<SegmentMap::const_iterator > KDL::TreeElement::children
parent
SegmentMap::const_iterator KDL::TreeElement::parent
q_nr
unsigned int KDL::TreeElement::q_nr
segment
Segment KDL::TreeElement::segment
The documentation for this class was generated from the following file:
src/tree.hpp