KDL: KDL::Trajectory_Stationary Class Reference
KDL::Trajectory_Stationary Class Reference
Motion
Implements a "trajectory" of a stationary position for an amount of time.
#include <src/trajectory_stationary.hpp>
Public Member Functions
Trajectory_Stationary (double _duration, const Frame &_pos)
virtual double Duration () const
virtual Frame Pos (double time) const
virtual Twist Vel (double time) const
virtual Twist Acc (double time) const
virtual void Write (std::ostream &os) const
virtual Trajectory * Clone () const
virtual ~Trajectory_Stationary ()
Static Public Member Functions
static Trajectory * Read (std::istream &is)
Private Attributes
double duration
Frame pos
Detailed Description
Implements a "trajectory" of a stationary position for an amount of time.
Constructor & Destructor Documentation
Trajectory_Stationary()
KDL::Trajectory_Stationary::Trajectory_Stationary (double _duration, const Frame & _pos) inline
~Trajectory_Stationary()
virtual KDL::Trajectory_Stationary::~Trajectory_Stationary () inline virtual
Member Function Documentation
Acc()
virtual Twist KDL::Trajectory_Stationary::Acc (double time) const inline virtual
Implements KDL::Trajectory.
References KDL::Twist::Zero().
Clone()
virtual Trajectory * KDL::Trajectory_Stationary::Clone () const inline virtual
Implements KDL::Trajectory.
References duration, and pos.
Duration()
virtual double KDL::Trajectory_Stationary::Duration () const inline virtual
Implements KDL::Trajectory.
References duration.
Pos()
virtual Frame KDL::Trajectory_Stationary::Pos (double time) const inline virtual
Implements KDL::Trajectory.
References pos.
Read()
Trajectory * KDL::Trajectory::Read (std::istream & is) static inherited
References KDL::Path::Read(), and KDL::VelocityProfile::Read().
Vel()
virtual Twist KDL::Trajectory_Stationary::Vel (double time) const inline virtual
Implements KDL::Trajectory.
References KDL::Twist::Zero().
Write()
void KDL::Trajectory_Stationary::Write (std::ostream & os) const virtual
Implements KDL::Trajectory.
References duration, and pos.
Member Data Documentation
duration
double KDL::Trajectory_Stationary::duration private
Referenced by Clone(), Duration(), and Write().
pos
Frame KDL::Trajectory_Stationary::pos private
Referenced by Clone(), Pos(), and Write().
The documentation for this class was generated from the following files:
src/trajectory_stationary.hpp
src/trajectory_stationary.cpp