KDL: KDL::TreeJntToJacSolver Class Reference
KDL::TreeJntToJacSolver Class Reference
#include <src/treejnttojacsolver.hpp>
Public Member Functions
TreeJntToJacSolver (const Tree &tree)
virtual ~TreeJntToJacSolver ()
int JntToJac (const JntArray &q_in, Jacobian &jac, const std::string &segmentname)
Private Attributes
KDL::Tree tree
Constructor & Destructor Documentation
TreeJntToJacSolver()
KDL::TreeJntToJacSolver::TreeJntToJacSolver (const Tree & tree) explicit
~TreeJntToJacSolver()
KDL::TreeJntToJacSolver::~TreeJntToJacSolver () virtual
Member Function Documentation
JntToJac()
int KDL::TreeJntToJacSolver::JntToJac (const JntArray & q_in, Jacobian & jac, const std::string & segmentname)
References KDL::changeBase(), KDL::Jacobian::columns(), KDL::Joint::Fixed, KDL::Tree::getNrOfJoints(), KDL::Tree::getRootSegment(), KDL::Tree::getSegments(), GetTreeElementParent, GetTreeElementQNr, GetTreeElementSegment, KDL::Frame::Identity(), KDL::Frame::M, KDL::Frame::p, KDL::Twist::RefPoint(), KDL::JntArray::rows(), KDL::Jacobian::setColumn(), KDL::SetToZero(), and tree.
Referenced by KDL::TreeIkSolverVel_wdls::CartToJnt().
Member Data Documentation
tree
KDL::Tree KDL::TreeJntToJacSolver::tree private
Referenced by JntToJac().
The documentation for this class was generated from the following files:
src/treejnttojacsolver.hpp
src/treejnttojacsolver.cpp