KDL: KDL::Trajectory Class Reference
KDL::Trajectory Class Reference abstract
Motion
An abstract class that implements a trajectory contains a cartesian space trajectory and an underlying velocity profile.
#include <src/trajectory.hpp>
Public Member Functions
virtual double Duration () const =0
virtual Frame Pos (double time) const =0
virtual Twist Vel (double time) const =0
virtual Twist Acc (double time) const =0
virtual Trajectory * Clone () const =0
virtual void Write (std::ostream &os) const =0
virtual ~Trajectory ()
Static Public Member Functions
static Trajectory * Read (std::istream &is)
Detailed Description
An abstract class that implements a trajectory contains a cartesian space trajectory and an underlying velocity profile.
Constructor & Destructor Documentation
~Trajectory()
virtual KDL::Trajectory::~Trajectory () inline virtual
Member Function Documentation
Acc()
virtual Twist KDL::Trajectory::Acc (double time) const pure virtual
Implemented in KDL::Trajectory_Composite, KDL::Trajectory_Segment, and KDL::Trajectory_Stationary.
Referenced by KDL::Trajectory_Composite::Acc().
Clone()
virtual Trajectory * KDL::Trajectory::Clone () const pure virtual
Implemented in KDL::Trajectory_Composite, KDL::Trajectory_Segment, and KDL::Trajectory_Stationary.
Duration()
virtual double KDL::Trajectory::Duration () const pure virtual
Implemented in KDL::Trajectory_Composite, KDL::Trajectory_Segment, and KDL::Trajectory_Stationary.
Referenced by KDL::Trajectory_Composite::Acc(), KDL::Trajectory_Composite::Add(), KDL::Trajectory_Composite::Pos(), and KDL::Trajectory_Composite::Vel().
Pos()
virtual Frame KDL::Trajectory::Pos (double time) const pure virtual
Implemented in KDL::Trajectory_Composite, KDL::Trajectory_Segment, and KDL::Trajectory_Stationary.
Referenced by KDL::Trajectory_Composite::Pos().
Read()
Trajectory * KDL::Trajectory::Read (std::istream & is) static
References KDL::Path::Read(), and KDL::VelocityProfile::Read().
Vel()
virtual Twist KDL::Trajectory::Vel (double time) const pure virtual
Implemented in KDL::Trajectory_Composite, KDL::Trajectory_Segment, and KDL::Trajectory_Stationary.
Referenced by KDL::Trajectory_Composite::Vel().
Write()
virtual void KDL::Trajectory::Write (std::ostream & os) const pure virtual
Implemented in KDL::Trajectory_Composite, KDL::Trajectory_Segment, and KDL::Trajectory_Stationary.
The documentation for this class was generated from the following files:
src/trajectory.hpp
src/trajectory.cpp