KDL: KDL::ChainFkSolverPos_recursive Class Reference
KDL::ChainFkSolverPos_recursive Class Reference
Kinematic Families
Implementation of a recursive forward position kinematics algorithm to calculate the position transformation from joint space to Cartesian space of a general kinematic chain (KDL::Chain).
#include <src/chainfksolverpos_recursive.hpp>
Public Types
enum {
E_DEGRADED = +1 , E_NOERROR = 0 , E_NO_CONVERGE = -1 , E_UNDEFINED = -2 ,
E_NOT_UP_TO_DATE = -3 , E_SIZE_MISMATCH = -4 , E_MAX_ITERATIONS_EXCEEDED = -5 , E_OUT_OF_RANGE = -6 ,
E_NOT_IMPLEMENTED = -7 , E_SVD_FAILED = -8
}
Public Member Functions
ChainFkSolverPos_recursive (const Chain &chain)
~ChainFkSolverPos_recursive ()
virtual int JntToCart (const JntArray &q_in, Frame &p_out, int segmentNr=-1)
Calculate forward position kinematics for a KDL::Chain, from joint coordinates to cartesian pose.
virtual int JntToCart (const JntArray &q_in, std::vector< Frame > &p_out, int segmentNr=-1)
Calculate forward position kinematics for a KDL::Chain, from joint coordinates to cartesian pose.
virtual void updateInternalDataStructures ()
Update the internal data structures.
virtual int getError () const
Return the latest error.
virtual const char * strError (const int error) const
Return a description of the latest error.
Protected Attributes
int error
Latest error, initialized to E_NOERROR in constructor.
Private Attributes
const Chain & chain
Detailed Description
Implementation of a recursive forward position kinematics algorithm to calculate the position transformation from joint space to Cartesian space of a general kinematic chain (KDL::Chain).
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
Enumerator
E_DEGRADED
Converged but degraded solution (e.g. WDLS with psuedo-inverse singular)
E_NOERROR
No error.
E_NO_CONVERGE
Failed to converge.
E_UNDEFINED
Undefined value (e.g. computed a NAN, or tan(90 degrees))
E_NOT_UP_TO_DATE
Chain size changed.
E_SIZE_MISMATCH
Input size does not match internal state.
E_MAX_ITERATIONS_EXCEEDED
Maximum number of iterations exceeded.
E_OUT_OF_RANGE
Requested index out of range.
E_NOT_IMPLEMENTED
Not yet implemented.
E_SVD_FAILED
Internal svd calculation failed.
Constructor & Destructor Documentation
ChainFkSolverPos_recursive()
KDL::ChainFkSolverPos_recursive::ChainFkSolverPos_recursive (const Chain & chain)
~ChainFkSolverPos_recursive()
KDL::ChainFkSolverPos_recursive::~ChainFkSolverPos_recursive ()
Member Function Documentation
getError()
virtual int KDL::SolverI::getError () const inline virtual inherited
Return the latest error.
References KDL::SolverI::error.
JntToCart() [1/2]
int KDL::ChainFkSolverPos_recursive::JntToCart (const JntArray & q_in, Frame & p_out, int segmentNr = -1) virtual
Calculate forward position kinematics for a KDL::Chain, from joint coordinates to cartesian pose.
Parameters
q_in input joint coordinates
p_out reference to output cartesian pose
Returns
if < 0 something went wrong
Implements KDL::ChainFkSolverPos.
References chain, KDL::SolverI::E_NOERROR, KDL::SolverI::E_OUT_OF_RANGE, KDL::SolverI::E_SIZE_MISMATCH, KDL::SolverI::error, KDL::Joint::Fixed, KDL::Segment::getJoint(), KDL::Chain::getNrOfJoints(), KDL::Chain::getNrOfSegments(), KDL::Chain::getSegment(), KDL::Joint::getType(), KDL::Frame::Identity(), KDL::Segment::pose(), and KDL::JntArray::rows().
Referenced by KDL::ChainExternalWrenchEstimator::JntToExtWrench(), and KDL::ChainJntToJacDotSolver::JntToJacDot().
JntToCart() [2/2]
int KDL::ChainFkSolverPos_recursive::JntToCart (const JntArray & q_in, std::vector< Frame > & p_out, int segmentNr = -1) virtual
Calculate forward position kinematics for a KDL::Chain, from joint coordinates to cartesian pose.
Parameters
q_in input joint coordinates
p_out reference to a vector of output cartesian poses for all segments
Returns
if < 0 something went wrong
Implements KDL::ChainFkSolverPos.
References chain, KDL::Joint::Fixed, KDL::Segment::getJoint(), KDL::Chain::getNrOfJoints(), KDL::Chain::getNrOfSegments(), KDL::Chain::getSegment(), KDL::Joint::getType(), KDL::Segment::pose(), and KDL::JntArray::rows().
strError()
virtual const char * KDL::SolverI::strError (const int error) const inline virtual inherited
Return a description of the latest error.
Returns
if error is known then a description of error, otherwise "UNKNOWN ERROR"
Reimplemented in KDL::ChainExternalWrenchEstimator, KDL::ChainIkSolverPos_LMA, KDL::ChainIkSolverPos_NR, KDL::ChainIkSolverPos_NR_JL, KDL::ChainIkSolverVel_pinv, KDL::ChainIkSolverVel_wdls, and KDL::ChainJntToJacDotSolver.
References KDL::SolverI::E_DEGRADED, KDL::SolverI::E_MAX_ITERATIONS_EXCEEDED, KDL::SolverI::E_NO_CONVERGE, KDL::SolverI::E_NOERROR, KDL::SolverI::E_NOT_IMPLEMENTED, KDL::SolverI::E_NOT_UP_TO_DATE, KDL::SolverI::E_OUT_OF_RANGE, KDL::SolverI::E_SIZE_MISMATCH, KDL::SolverI::E_SVD_FAILED, KDL::SolverI::E_UNDEFINED, and KDL::SolverI::error.
Referenced by KDL::ChainExternalWrenchEstimator::strError(), KDL::ChainIkSolverPos_LMA::strError(), KDL::ChainIkSolverPos_NR::strError(), KDL::ChainIkSolverPos_NR_JL::strError(), KDL::ChainIkSolverVel_pinv::strError(), KDL::ChainIkSolverVel_wdls::strError(), and KDL::ChainJntToJacDotSolver::strError().
updateInternalDataStructures()
virtual void KDL::ChainFkSolverPos_recursive::updateInternalDataStructures () inline virtual
Update the internal data structures.
This is required if the number of segments or number of joints of a chain/tree have changed. This provides a single point of contact for solver memory allocations.
Implements KDL::ChainFkSolverPos.
Referenced by KDL::ChainExternalWrenchEstimator::updateInternalDataStructures(), and KDL::ChainJntToJacDotSolver::updateInternalDataStructures().
Member Data Documentation
chain
const Chain& KDL::ChainFkSolverPos_recursive::chain private
Referenced by JntToCart(), and JntToCart().
error
int KDL::SolverI::error protected inherited
Latest error, initialized to E_NOERROR in constructor.
Referenced by KDL::ChainIkSolverVel_pinv::CartToJnt(), KDL::ChainIkSolverVel_pinv_givens::CartToJnt(), KDL::ChainIkSolverVel_pinv_nso::CartToJnt(), KDL::ChainIdSolver_RNE::CartToJnt(), KDL::TreeIdSolver_RNE::CartToJnt(), KDL::ChainFdSolver_RNE::CartToJnt(), KDL::ChainHdSolver_Vereshchagin::CartToJnt(), KDL::ChainIkSolverVel_pinv::CartToJnt(), KDL::ChainIkSolverVel_pinv_givens::CartToJnt(), KDL::ChainIkSolverVel_pinv_nso::CartToJnt(), KDL::ChainIkSolverVel_wdls::CartToJnt(), KDL::ChainIkSolverPos_NR::CartToJnt(), KDL::ChainIkSolverPos_NR_JL::CartToJnt(), KDL::ChainIkSolverPos_LMA::CartToJnt(), KDL::SolverI::getError(), KDL::ChainIkSolverVel_wdls::getSigma(), JntToCart(), KDL::ChainFkSolverVel_recursive::JntToCart(), KDL::ChainExternalWrenchEstimator::JntToExtWrench(), KDL::ChainJntToJacSolver::JntToJac(), KDL::ChainJntToJacDotSolver::JntToJacDot(), KDL::ChainJntToJacDotSolver::JntToJacDot(), KDL::ChainDynParam::JntToMass(), KDL::ChainExternalWrenchEstimator::setInitialMomentum(), KDL::ChainIkSolverPos_NR_JL::setJointLimits(), KDL::ChainJntToJacDotSolver::setLockedJoints(), KDL::ChainJntToJacSolver::setLockedJoints(), KDL::ChainIkSolverVel_pinv_nso::setOptPos(), KDL::ChainIkSolverVel_wdls::setWeightJS(), KDL::ChainIkSolverVel_pinv_nso::setWeights(), KDL::ChainIkSolverVel_wdls::setWeightTS(), KDL::ChainExternalWrenchEstimator::strError(), KDL::ChainIkSolverPos_LMA::strError(), KDL::ChainIkSolverPos_NR::strError(), KDL::ChainIkSolverPos_NR_JL::strError(), KDL::ChainIkSolverVel_pinv::strError(), KDL::ChainIkSolverVel_wdls::strError(), KDL::ChainJntToJacDotSolver::strError(), and KDL::SolverI::strError().
The documentation for this class was generated from the following files:
src/chainfksolverpos_recursive.hpp
src/chainfksolverpos_recursive.cpp