KDL: src/framevel.inl File Reference
framevel.inl File Reference
Functions
FrameVel operator* (const FrameVel &lhs, const FrameVel &rhs)
FrameVel operator* (const FrameVel &lhs, const Frame &rhs)
FrameVel operator* (const Frame &lhs, const FrameVel &rhs)
bool Equal (const FrameVel &r1, const FrameVel &r2, double eps)
bool Equal (const Frame &r1, const FrameVel &r2, double eps)
bool Equal (const FrameVel &r1, const Frame &r2, double eps)
bool operator== (const FrameVel &r1, const FrameVel &r2)
bool operator!= (const FrameVel &r1, const FrameVel &r2)
bool operator== (const Frame &r1, const FrameVel &r2)
bool operator!= (const Frame &r1, const FrameVel &r2)
bool operator== (const FrameVel &r1, const Frame &r2)
bool operator!= (const FrameVel &r1, const Frame &r2)
RotationVel operator* (const RotationVel &r1, const RotationVel &r2)
RotationVel operator* (const Rotation &r1, const RotationVel &r2)
RotationVel operator* (const RotationVel &r1, const Rotation &r2)
VectorVel operator+ (const VectorVel &r1, const VectorVel &r2)
VectorVel operator- (const VectorVel &r1, const VectorVel &r2)
VectorVel operator+ (const VectorVel &r1, const Vector &r2)
VectorVel operator- (const VectorVel &r1, const Vector &r2)
VectorVel operator+ (const Vector &r1, const VectorVel &r2)
VectorVel operator- (const Vector &r1, const VectorVel &r2)
VectorVel operator- (const VectorVel &r)
void SetToZero (VectorVel &v)
VectorVel operator* (const VectorVel &r1, const VectorVel &r2)
VectorVel operator* (const VectorVel &r1, const Vector &r2)
VectorVel operator* (const Vector &r1, const VectorVel &r2)
VectorVel operator* (double r1, const VectorVel &r2)
VectorVel operator* (const VectorVel &r1, double r2)
VectorVel operator* (const doubleVel &r1, const VectorVel &r2)
VectorVel operator* (const VectorVel &r2, const doubleVel &r1)
VectorVel operator/ (const VectorVel &r1, double r2)
VectorVel operator/ (const VectorVel &r2, const doubleVel &r1)
VectorVel operator* (const Rotation &R, const VectorVel &x)
bool Equal (const VectorVel &r1, const VectorVel &r2, double eps)
bool Equal (const Vector &r1, const VectorVel &r2, double eps)
bool Equal (const VectorVel &r1, const Vector &r2, double eps)
bool operator== (const VectorVel &r1, const VectorVel &r2)
bool operator!= (const VectorVel &r1, const VectorVel &r2)
bool operator== (const Vector &r1, const VectorVel &r2)
bool operator!= (const Vector &r1, const VectorVel &r2)
bool operator== (const VectorVel &r1, const Vector &r2)
bool operator!= (const VectorVel &r1, const Vector &r2)
bool Equal (const RotationVel &r1, const RotationVel &r2, double eps)
bool Equal (const Rotation &r1, const RotationVel &r2, double eps)
bool Equal (const RotationVel &r1, const Rotation &r2, double eps)
bool operator== (const RotationVel &r1, const RotationVel &r2)
bool operator!= (const RotationVel &r1, const RotationVel &r2)
bool operator== (const Rotation &r1, const RotationVel &r2)
bool operator!= (const Rotation &r1, const RotationVel &r2)
bool operator== (const RotationVel &r1, const Rotation &r2)
bool operator!= (const RotationVel &r1, const Rotation &r2)
bool Equal (const TwistVel &a, const TwistVel &b, double eps)
bool Equal (const Twist &a, const TwistVel &b, double eps)
bool Equal (const TwistVel &a, const Twist &b, double eps)
bool operator== (const TwistVel &a, const TwistVel &b)
bool operator!= (const TwistVel &a, const TwistVel &b)
bool operator== (const Twist &a, const TwistVel &b)
bool operator!= (const Twist &r1, const TwistVel &r2)
bool operator== (const TwistVel &r1, const Twist &r2)
bool operator!= (const TwistVel &r1, const Twist &r2)
IMETHOD doubleVel dot (const VectorVel &lhs, const VectorVel &rhs)
IMETHOD doubleVel dot (const VectorVel &lhs, const Vector &rhs)
IMETHOD doubleVel dot (const Vector &lhs, const VectorVel &rhs)
TwistVel operator* (const TwistVel &lhs, double rhs)
TwistVel operator* (double lhs, const TwistVel &rhs)
TwistVel operator/ (const TwistVel &lhs, double rhs)
TwistVel operator* (const TwistVel &lhs, const doubleVel &rhs)
TwistVel operator* (const doubleVel &lhs, const TwistVel &rhs)
TwistVel operator/ (const TwistVel &lhs, const doubleVel &rhs)
TwistVel operator+ (const TwistVel &lhs, const TwistVel &rhs)
TwistVel operator- (const TwistVel &lhs, const TwistVel &rhs)
TwistVel operator- (const TwistVel &arg)
void SetToZero (TwistVel &v)
Function Documentation
dot() [1/3]
IMETHOD doubleVel dot (const Vector & lhs, const VectorVel & rhs)
References dot().
dot() [2/3]
IMETHOD doubleVel dot (const VectorVel & lhs, const Vector & rhs)
References dot().
dot() [3/3]
IMETHOD doubleVel dot (const VectorVel & lhs, const VectorVel & rhs)
References dot().
Referenced by dot(), dot(), dot(), and KDL::VectorVel::Norm().
Equal() [1/12]
bool Equal (const Frame & r1, const FrameVel & r2, double eps)
References Equal().
Equal() [2/12]
bool Equal (const FrameVel & r1, const Frame & r2, double eps)
References Equal().
Equal() [3/12]
bool Equal (const FrameVel & r1, const FrameVel & r2, double eps)
References Equal().
Referenced by Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), Equal(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), and operator==().
Equal() [4/12]
bool Equal (const Rotation & r1, const RotationVel & r2, double eps)
References Equal().
Equal() [5/12]
bool Equal (const RotationVel & r1, const Rotation & r2, double eps)
References Equal().
Equal() [6/12]
bool Equal (const RotationVel & r1, const RotationVel & r2, double eps)
References Equal().
Equal() [7/12]
bool Equal (const Twist & a, const TwistVel & b, double eps)
References Equal().
Equal() [8/12]
bool Equal (const TwistVel & a, const Twist & b, double eps)
References Equal().
Equal() [9/12]
bool Equal (const TwistVel & a, const TwistVel & b, double eps)
References Equal().
Equal() [10/12]
bool Equal (const Vector & r1, const VectorVel & r2, double eps)
References Equal().
Equal() [11/12]
bool Equal (const VectorVel & r1, const Vector & r2, double eps)
References Equal().
Equal() [12/12]
bool Equal (const VectorVel & r1, const VectorVel & r2, double eps)
References Equal().
operator!=() [1/12]
bool operator!= (const Frame & r1, const FrameVel & r2)
References operator==().
operator!=() [2/12]
bool operator!= (const FrameVel & r1, const Frame & r2)
References operator==().
operator!=() [3/12]
bool operator!= (const FrameVel & r1, const FrameVel & r2)
References operator==().
operator!=() [4/12]
bool operator!= (const Rotation & r1, const RotationVel & r2)
References operator==().
operator!=() [5/12]
bool operator!= (const RotationVel & r1, const Rotation & r2)
References operator==().
operator!=() [6/12]
bool operator!= (const RotationVel & r1, const RotationVel & r2)
References operator==().
operator!=() [7/12]
bool operator!= (const Twist & r1, const TwistVel & r2)
References operator==().
operator!=() [8/12]
bool operator!= (const TwistVel & a, const TwistVel & b)
References operator==().
operator!=() [9/12]
bool operator!= (const TwistVel & r1, const Twist & r2)
References operator==().
operator!=() [10/12]
bool operator!= (const Vector & r1, const VectorVel & r2)
References operator==().
operator!=() [11/12]
bool operator!= (const VectorVel & r1, const Vector & r2)
References operator==().
operator!=() [12/12]
bool operator!= (const VectorVel & r1, const VectorVel & r2)
References operator==().
operator*() [1/18]
TwistVel operator* (const doubleVel & lhs, const TwistVel & rhs)
operator*() [2/18]
VectorVel operator* (const doubleVel & r1, const VectorVel & r2)
operator*() [3/18]
FrameVel operator* (const Frame & lhs, const FrameVel & rhs)
operator*() [4/18]
FrameVel operator* (const FrameVel & lhs, const Frame & rhs)
operator*() [5/18]
FrameVel operator* (const FrameVel & lhs, const FrameVel & rhs)
operator*() [6/18]
VectorVel operator* (const Rotation & R, const VectorVel & x)
operator*() [7/18]
RotationVel operator* (const Rotation & r1, const RotationVel & r2)
operator*() [8/18]
RotationVel operator* (const RotationVel & r1, const Rotation & r2)
operator*() [9/18]
RotationVel operator* (const RotationVel & r1, const RotationVel & r2)
operator*() [10/18]
TwistVel operator* (const TwistVel & lhs, const doubleVel & rhs)
operator*() [11/18]
TwistVel operator* (const TwistVel & lhs, double rhs)
operator*() [12/18]
VectorVel operator* (const Vector & r1, const VectorVel & r2)
operator*() [13/18]
VectorVel operator* (const VectorVel & r1, const Vector & r2)
operator*() [14/18]
VectorVel operator* (const VectorVel & r1, const VectorVel & r2)
operator*() [15/18]
VectorVel operator* (const VectorVel & r1, double r2)
operator*() [16/18]
VectorVel operator* (const VectorVel & r2, const doubleVel & r1)
operator*() [17/18]
TwistVel operator* (double lhs, const TwistVel & rhs)
operator*() [18/18]
VectorVel operator* (double r1, const VectorVel & r2)
operator+() [1/4]
TwistVel operator+ (const TwistVel & lhs, const TwistVel & rhs)
operator+() [2/4]
VectorVel operator+ (const Vector & r1, const VectorVel & r2)
operator+() [3/4]
VectorVel operator+ (const VectorVel & r1, const Vector & r2)
operator+() [4/4]
VectorVel operator+ (const VectorVel & r1, const VectorVel & r2)
operator-() [1/6]
TwistVel operator- (const TwistVel & arg)
operator-() [2/6]
TwistVel operator- (const TwistVel & lhs, const TwistVel & rhs)
operator-() [3/6]
VectorVel operator- (const Vector & r1, const VectorVel & r2)
operator-() [4/6]
VectorVel operator- (const VectorVel & r)
operator-() [5/6]
VectorVel operator- (const VectorVel & r1, const Vector & r2)
operator-() [6/6]
VectorVel operator- (const VectorVel & r1, const VectorVel & r2)
operator/() [1/4]
TwistVel operator/ (const TwistVel & lhs, const doubleVel & rhs)
operator/() [2/4]
TwistVel operator/ (const TwistVel & lhs, double rhs)
operator/() [3/4]
VectorVel operator/ (const VectorVel & r1, double r2)
operator/() [4/4]
VectorVel operator/ (const VectorVel & r2, const doubleVel & r1)
operator==() [1/12]
bool operator== (const Frame & r1, const FrameVel & r2)
References Equal().
operator==() [2/12]
bool operator== (const FrameVel & r1, const Frame & r2)
References Equal().
operator==() [3/12]
bool operator== (const FrameVel & r1, const FrameVel & r2)
References Equal().
Referenced by operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), and operator!=().
operator==() [4/12]
bool operator== (const Rotation & r1, const RotationVel & r2)
References Equal().
operator==() [5/12]
bool operator== (const RotationVel & r1, const Rotation & r2)
References Equal().
operator==() [6/12]
bool operator== (const RotationVel & r1, const RotationVel & r2)
References Equal().
operator==() [7/12]
bool operator== (const Twist & a, const TwistVel & b)
References Equal().
operator==() [8/12]
bool operator== (const TwistVel & a, const TwistVel & b)
References Equal().
operator==() [9/12]
bool operator== (const TwistVel & r1, const Twist & r2)
References Equal().
operator==() [10/12]
bool operator== (const Vector & r1, const VectorVel & r2)
References Equal().
operator==() [11/12]
bool operator== (const VectorVel & r1, const Vector & r2)
References Equal().
operator==() [12/12]
bool operator== (const VectorVel & r1, const VectorVel & r2)
References Equal().
SetToZero() [1/2]
void SetToZero (TwistVel & v)
References SetToZero().
SetToZero() [2/2]
void SetToZero (VectorVel & v)
References SetToZero().
Referenced by SetToZero(), and SetToZero().