controller_list:
  - name: fake_arm_controller
    joints:
      - servo_link2
      - con_up_1
      - con_up_2
      - con_up_3
  - name: fake_hand_controller
    joints:
      - rotation_grip
      - plan_move
  - name: fake_armhand_controller
    joints:
      - servo_link2
      - con_up_1
      - con_up_2
      - con_up_3
      - rotation_grip
      - plan_move