controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


braccio_controller:
  ros__parameters:
    type: ros2_control/BraccioController
    joints:
      - arm_rot
      - arm_1_up_down
      - arm_2_up_down
      - arm_3_up_down
      - rot_grasp
      - grasp

    command_interfaces:
      - position

    state_interfaces:
      - position
